### ISSUE TITLE
CSS `backdrop-filter` affects photo gallery scrolling animations FPS (+ other places)

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#212]
**Describe the bug**

Swiping photos is unpleasant experience due to FPS drops

- Which site: dev.phanpy.social

**To Reproduce**
1. Go to post with multiple photos, e.g https://dev.phanpy.social/#/mstdn.social/s/110885138853427849
2. Preview first photo
3. Swipe to next photo
4. Observe FPS drops during this action

P.S. you can hide control elements, by tapping photo. After hiding – FPS is no longer dropping (because .plain2, plain3 class elements are hidden)

<hr>
Comment out these two styles and gallery animation framerate will dramatically increase. 

I guess this happens because of `transparent` + blur() on moving photos, which consumes a lot of CPU on each frame

Ref: https://github.com/cheeaun/phanpy/blob/main/src/index.css#L199

```css
:is(button, .button).plain2 {
  background-color: transparent;
  color: var(--link-color);
  /* backdrop-filter: blur(12px) invert(0.1); */
}
:is(button, .button).plain3 {
  background-color: transparent;
  color: var(--button-text-color);
  /* backdrop-filter: blur(12px) invert(0.25); */
}
```

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android 14
 - Browser Google Chrome 115

**Additional context**
I have checked locally, that removing those `backdrop-filter` solves problem, but i'm not a frontend guy, so i don't know how to correctly replace them with somewhat similar
