### ISSUE TITLE
content-visibility: auto

### ISSUE THREAD

**Issue by felix9** [cheeaun/phanpy#861]
phanpy gets a little sluggish when I scroll far down a timeline. today, on a hunch I added a userstyle
```css
article { content-visibility: auto; }
```
which tells the browser that articles are self-contained boxes that don't have layout implications outside the box, and the contents can be ignored when not visible. this seems to help? (I haven't measured anything)
