### ISSUE TITLE
[FR] Adjustable column width

### ISSUE THREAD

**Issue by nhan000** [cheeaun/phanpy#95]
I have 6 shortcuts in the form of multi-column and because Phanpy tries to fit them all on the screen, each column becomes very narrow.

It'd be great if you could allow users to set column width. I like having everything laid out instead of having to click through these buttons and use "shift+scroll" to scroll between columns.

Thanks a lot for this great app!

**Comment by nhan000** [comment]
for those who're interested in a temporary fix: I'm using [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) plugin with the following code to achieve the look below. (I want it to be functional over aesthetics and I don't know CSS so the code may look funky).

<details>
  <summary>Click to reveal code block</summary>

```
#columns>* {
    flex-basis: min(100vw,60em);
}

@media (min-width: 40em)
    #columns {
    }

	#columns li:has(.status-carousel) {
        width: 57em;
        -webkit-transform: translateX(calc(-50% + 20em));
        transform: translate(calc(-50% + 20em))
    }
}

.filter-bar>a>.filter-count {
}

@media (min-width: 40em) {
    li:has(.status-carousel) {
        width: 95vw;
        max-width: 1000em;
        -webkit-transform: translateX(calc(-50% + 20em));
        transform: translate(calc(-50% + 20em))
    }
}
```
</details>

Profile page layout
![image](https://user-images.githubusercontent.com/85216095/234536530-b6c4a075-848b-4746-bf04-d087868f1438.png)

Multi-colum layout
![image](https://user-images.githubusercontent.com/85216095/234536657-eb895f02-f866-4e1a-8d7d-ed4e10129344.png)

**Comment by abominabledrh** [comment]
I don't know how feasible this is but as a user's screen is an unknown size, rather than an option to define column width would it be possible to define the number of columns visible - with other columns accessible by scrolling?

**Comment by zachpmanson** [comment]
This is my only complaint with phanpy. Being able to increase the width of columns would increase usability greatly.

**Comment by zachpmanson** [comment]
Current CSS defining width is this in `app.css`

```css
#columns > * {
  overscroll-behavior: auto;
  scroll-snap-align: left;
  scroll-snap-stop: always;
  overscroll-behavior: auto;
  flex-basis: min(100vw, 360px);
  flex-shrink: 0;
  box-shadow: -1px 0 var(--bg-color), -2px 0 var(--drop-shadow-color),
    -3px 0 var(--bg-color);
}
```

https://github.com/cheeaun/phanpy/blob/4c0bc62ad016eb36e7e1bd909fc21728bee1f0c4/src/app.css#L2439

Can write a custom user stylesheet to set this to what you want, as a workaround.  Would love this width to be a user editable setting.
